<?php
/**
 * @file
 *
 */

/**
 * Implements hook_init().
 */
function artesis_facebookshare_init() {
  global $base_url;
  drupal_add_js('misc/jquery.form.js');
  drupal_add_library('system', 'drupal.ajax');
  drupal_add_js(array('artesis_facebookshare' => array('base_url' => $base_url)), 'setting');
}

/**
 * Implements hook_menu().
 */
function artesis_facebookshare_menu() {
  // Menu callback.
  $items['artesis_facebookshare/json'] = array(
    'page callback' => 'artesis_facebookshare_json_response',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * @return string
 *   Returns the HTML that represents the facebook share for the specific page,
 *   in a json encoding.
 */
function artesis_facebookshare_json_response() {
  $params = drupal_get_query_parameters();
  $url = $params['url'] ? $params['url'] : '';
  return drupal_json_output(theme_artesis_facebookshare($url));
}

/**
 * Returns html of share count.
 *
 * @param string $url
 *   The url whose share's on facebook we will check.
 *
 * @return string
 *   Representing the html code for the shares of the specific URL.
 *   Returns an empty string on service's fail.
 */
function theme_artesis_facebookshare($url) {
  $url = "https://api.facebook.com/restserver.php?method=links.getStats&urls=" . urlencode($url);
  // Return no content to be appended in case something fails.
  $output = '';
  $xml_file_contents = file_get_contents($url);
  if ($xml_file_contents) {
    $xml = simplexml_load_string($xml_file_contents);
    if ($xml && isset($xml->link_stat->share_count)) {
      // Get page shares.
      $output = '<div class="artesis-facebookshare-count">' . $xml->link_stat->share_count . '</div>';
    }
  }
  return $output;
}

/**
 * Implements hook_preprocess_page().
 * Removes delete button on non-nodelist panes for
 * certain use role (IPE_RESTRICTED_ROLE).
 * Additionally, it adds open graph metadata for
 * pages searchResult, ting object and ting collection.
 */
function artesis_facebookshare_preprocess_page($page) {
  $user = $GLOBALS['user'];

  // Detect different pages and add the appropriate open graph metadata.
  $og_elements = array();
  $og_title = '';
  $og_description = '';
  $og_imageurl = '';
  $og_url = '';
  if (arg(0) == 'ting' && arg(1) == 'object' && arg(2) != NULL) {
    $ting_entity = ting_object_load(arg(2));

    if (isset($ting_entity->ting_cover['und'][0]['local_id'])) {
      $uri = ting_covers_object_path($ting_entity->ting_cover['und'][0]['local_id']);
      $wrapper = file_stream_wrapper_get_instance_by_uri($uri);
      if ($wrapper) {
        $og_imageurl = $wrapper->getExternalUrl();
      }
    }
    if (isset($ting_entity->reply->record['dc:title'])) {
      if (isset($ting_entity->reply->record['dc:title'][0])) {
        if (is_string($ting_entity->reply->record['dc:title'][0])) {
          $og_title = $ting_entity->reply->record['dc:title'][0];
        }
        elseif (is_array($ting_entity->reply->record['dc:title'][0])) {
          if (isset($ting_entity->reply->record['dc:title'][0][0])) {
            $og_title = $ting_entity->reply->record['dc:title'][0][0];
          }
        }
      }
      elseif (isset($ting_entity->reply->record['dc:title']['dkdcplus:full'][0])) {
        $og_title = $ting_entity->reply->record['dc:title']['dkdcplus:full'][0];
      }
    }
    if (isset($ting_entity->reply->record['dcterms:abstract']) && is_array($ting_entity->reply->record['dcterms:abstract'])) {
      $abstract_array = array_shift(array_values($ting_entity->reply->record['dcterms:abstract']));
      if (isset($abstract_array[0])) {
        $og_description = $abstract_array[0];
      }
    }
    $og_url = url(NULL, array('absolute' => TRUE)) . current_path();
  }
  elseif (arg(0) == 'ting' && arg(1) == 'collection' && arg(2) != NULL) {
    $ting_collection = ting_object_load(arg(2));
    if (isset($ting_collection->ting_cover['und'][0]['local_id'])) {
      $uri = ting_covers_object_path($ting_collection->ting_cover['und'][0]['local_id']);
      $wrapper = file_stream_wrapper_get_instance_by_uri($uri);
      if ($wrapper) {
        $og_imageurl = $wrapper->getExternalUrl();
      }
    }
    if (count($ting_collection->reply->record['dc:title']) > 0 ) {
      $first_title_element = array_shift(array_values($ting_collection->reply->record['dc:title']));
      if (isset($first_title_element[0])) {
        if (is_string($first_title_element[0])) {
          $og_title = $first_title_element[0];
        }
      }
      elseif (isset($ting_collection->reply->record['dc:title']['dkdcplus:full'][0])) {
        if (is_string($ting_collection->reply->record['dc:title']['dkdcplus:full'][0])) {
          $og_title = $ting_collection->reply->record['dc:title']['dkdcplus:full'][0];
        }
      }
    }
    if (isset($ting_collection->reply->record['dcterms:abstract']) && is_array($ting_collection->reply->record['dcterms:abstract'])) {
      $abstract_array = array_shift(array_values($ting_collection->reply->record['dcterms:abstract']));
      if (isset($abstract_array[0])) {
        $og_description = $abstract_array[0];
      }
    }
    $og_url = url(NULL, array('absolute' => TRUE)) . current_path();
  }
  elseif (arg(0) == 'search' && arg(1) == 'ting') {
    $og_title = t('Search results');
    $og_description = arg(2) != NULL ? t('Search results for') . ' ' . arg(2) . '.' : url(NULL, array('absolute' => TRUE)) . current_path();
    $og_url = url(NULL, array('absolute' => TRUE)) . current_path();
  }

  if ($og_title !='') {
    $og_elements['og_title'] = array(
      '#tag' => 'meta',
      '#attributes' => array(
        'property' => 'og:title',
        'content' => $og_title,
      ),
    );
  }

  if ($og_description != '') {
    $og_elements['og_description'] = array(
      '#tag' => 'meta',
      '#attributes' => array(
        'property' => 'og:description',
        'content' => $og_description,
      ),
    );
  }

  // @todo find a way to retrieve this.
  if ($og_imageurl != '') {
    $og_elements['og_image'] = array(
      '#tag' => 'meta',
      '#attributes' => array(
        'property' => 'og:image',
        'content' => $og_imageurl,
      ),
    );
  }
  if ($og_url != '') {
    $og_elements['og_url'] = array(
      '#tag' => 'meta',
      '#attributes' => array(
        'property' => 'og:url',
        'content' => $og_url,
      ),
    );
  }
  if (!empty($og_elements)) {
    foreach ($og_elements as $key => $og_element) {
          drupal_add_html_head($og_element, $key);
    }
  }

  if (in_array(IPE_RESTRICTED_ROLE, $user->roles)) {
    $protected_panes = drupal_static('artesis_frontend_ipe', array());
    $panes_selector = array();
    foreach ($protected_panes as $pane_id) {
      $panes_selector[] = 'pane-delete-panel-pane-' . $pane_id;
    }
    if (count($panes_selector)) {
      drupal_add_js('(function($) { $(document).ready(function() { $("#' . join(', #', $panes_selector) . '").parent().remove(); }) })(jQuery);', 'inline');
    }
  }
}