<?php

/**
 * @file
 * Facebook Share module functionality.
 */

/**
 * Implements hook_block_info().
 */
function facebookshare_block_info() {
  $blocks['facebook_share'] = array(
    'info' => t('Facebook share'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function facebookshare_block_view($delta = '') {
  global $base_url;
  $block = array();

  // Prevent displaying on admin pages.
  if (path_is_admin(current_path())) {
    return $block;
  }

  switch ($delta) {
    case 'facebook_share':
      $current_page = $base_url . '/' . current_path();
      $share_link = 'https://www.facebook.com/sharer/sharer.php?u=' . $current_page;

      $fb_link = l(t('Share on Facebook'), $share_link,
        array(
          'external' => TRUE,
          'attributes' => array(
            'class' => array(
              'fb-share',
            ),
            'target'=>'_blank'
          ),
        )
      );

      $block['content'] = $fb_link;
      break;
  }

  return $block;
}

/**
 * Implements hook_preprocess_page().
 *
 * Additionally, it adds open graph metadata for
 * pages searchResult, ting object and ting collection.
 */
function facebookshare_preprocess_html($variables) {
  $user = $GLOBALS['user'];
  $path = drupal_get_path('module', 'facebookshare') . '/css/easyddb_facebookshare.css';
  drupal_add_css($path);

  // Detect different pages and add the appropriate open graph metadata.
  $og_elements = array();
  $og_title = '';
  $og_description = '';
  $og_imageurl = '';
  $og_url = '';

  if (arg(0) == 'ting' && arg(1) == 'object' && arg(2) != NULL) {
    $ting_entity = ting_object_load(arg(2));

    if (isset($ting_entity->ting_cover['und'][0]['local_id'])) {
      $uri = ting_covers_object_path($ting_entity->ting_cover['und'][0]['local_id']);
      $wrapper = file_stream_wrapper_get_instance_by_uri($uri);
      if ($wrapper) {
        $og_imageurl = $wrapper->getExternalUrl();
      }
    }
    if (isset($ting_entity->reply->record['dc:title'])) {
      if (isset($ting_entity->reply->record['dc:title'][0])) {
        if (is_string($ting_entity->reply->record['dc:title'][0])) {
          $og_title = $ting_entity->reply->record['dc:title'][0];
        }
        elseif (is_array($ting_entity->reply->record['dc:title'][0])) {
          if (isset($ting_entity->reply->record['dc:title'][0][0])) {
            $og_title = $ting_entity->reply->record['dc:title'][0][0];
          }
        }
      }
      elseif (isset($ting_entity->reply->record['dc:title']['dkdcplus:full'][0])) {
        $og_title = $ting_entity->reply->record['dc:title']['dkdcplus:full'][0];
      }
    }
    if (isset($ting_entity->reply->record['dcterms:abstract']) && is_array($ting_entity->reply->record['dcterms:abstract'])) {
      $abstract_array = array_values($ting_entity->reply->record['dcterms:abstract']);
      $abstract_array = array_shift($abstract_array);
      if (isset($abstract_array[0])) {
        $og_description = $abstract_array[0];
      }
    }
    $og_url = url(NULL, array('absolute' => TRUE)) . current_path();
  }
  elseif (arg(0) == 'ting' && arg(1) == 'collection' && arg(2) != NULL) {
    $ting_collection = ting_object_load(arg(2));
    if (isset($ting_collection->ting_cover['und'][0]['local_id'])) {
      $uri = ting_covers_object_path($ting_collection->ting_cover['und'][0]['local_id']);
      $wrapper = file_stream_wrapper_get_instance_by_uri($uri);
      if ($wrapper) {
        $og_imageurl = $wrapper->getExternalUrl();
      }
    }
    if (count($ting_collection->reply->record['dc:title']) > 0) {
      $first_title_element = array_values($ting_collection->reply->record['dc:title']);
      $first_title_element = array_shift($first_title_element);
      if (isset($first_title_element[0])) {
        if (is_string($first_title_element[0])) {
          $og_title = $first_title_element[0];
        }
      }
      elseif (isset($ting_collection->reply->record['dc:title']['dkdcplus:full'][0])) {
        if (is_string($ting_collection->reply->record['dc:title']['dkdcplus:full'][0])) {
          $og_title = $ting_collection->reply->record['dc:title']['dkdcplus:full'][0];
        }
      }
    }
    if (isset($ting_collection->reply->record['dcterms:abstract']) && is_array($ting_collection->reply->record['dcterms:abstract'])) {
      $abstract_array = array_values($ting_collection->reply->record['dcterms:abstract']);
      $abstract_array = array_shift($abstract_array);
      if (isset($abstract_array[0])) {
        $og_description = $abstract_array[0];
      }
    }
    $og_url = url(NULL, array('absolute' => TRUE)) . current_path();
  }
  elseif (arg(0) == 'search' && arg(1) == 'ting') {
    $og_title = t('Search results');
    $og_description = arg(2) != NULL ? t('Search results for') . ' ' . arg(2) . '.' : url(NULL, array('absolute' => TRUE)) . current_path();
    $og_url = url(NULL, array('absolute' => TRUE)) . current_path();
  }

  if ($og_title != '') {
    $og_elements['og_title'] = array(
      '#tag' => 'meta',
      '#attributes' => array(
        'property' => 'og:title',
        'content' => $og_title,
      ),
    );
  }

  if ($og_description != '') {
    $og_elements['og_description'] = array(
      '#tag' => 'meta',
      '#attributes' => array(
        'property' => 'og:description',
        'content' => $og_description,
      ),
    );
  }

  // @todo find a way to retrieve this.
  if ($og_imageurl != '') {
    $og_elements['og_image'] = array(
      '#tag' => 'meta',
      '#attributes' => array(
        'property' => 'og:image',
        'content' => $og_imageurl,
      ),
    );
  }
  if ($og_url != '') {
    $og_elements['og_url'] = array(
      '#tag' => 'meta',
      '#attributes' => array(
        'property' => 'og:url',
        'content' => $og_url,
      ),
    );
  }
  if (!empty($og_elements)) {
    foreach ($og_elements as $key => $og_element) {
      drupal_add_html_head($og_element, $key);
    }
  }
}
